//! # M14: Phase Messaging
//!
//! Five `PhaseMessage` types for inter-sphere communication.
//! Messages can influence phase, coupling, or coordination.
//!
//! ## Layer: L3 (Field)
//! ## Module: M14
//! ## Dependencies: L1 (M01 types, M06 validation)

use serde::{Deserialize, Serialize};

use crate::m1_foundation::{
    m01_core_types::{phase_diff, PaneId},
    m06_validation::truncate_string,
};

// ──────────────────────────────────────────────────────────────
// PhaseMessage enum
// ──────────────────────────────────────────────────────────────

/// Phase-modulated inter-sphere message types.
///
/// Messages are generated by the field decision engine, conductor, or explicit
/// sphere-to-sphere communication. Each variant may or may not have a phase effect.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum PhaseMessage {
    /// Steer two spheres' phases closer together (attention alignment).
    AttentionAlignment {
        /// Sender sphere.
        from: PaneId,
        /// Target sphere.
        to: PaneId,
        /// Reason for alignment.
        context: String,
    },

    /// Request chimera formation (phase separation) between two spheres.
    ChimeraRequest {
        /// Sender sphere.
        from: PaneId,
        /// Target sphere.
        to: PaneId,
        /// Reason for chimera request.
        reason: String,
    },

    /// Shared write notification (consensus coordination).
    ConsensusWrite {
        /// Sender sphere.
        from: PaneId,
        /// Target sphere.
        to: PaneId,
        /// Payload (e.g. file path, task description).
        payload: String,
    },

    /// Emergency coherence: pull multiple targets toward sender's phase.
    EmergencyCoherence {
        /// Sender sphere initiating emergency.
        from: PaneId,
        /// Target spheres (capped at 50 per C12).
        targets: Vec<PaneId>,
        /// Reason for emergency.
        reason: String,
    },

    /// Resonance match: two spheres discovered overlapping buoys (tunnel).
    ResonanceMatch {
        /// Sender sphere.
        from: PaneId,
        /// Target sphere.
        to: PaneId,
        /// Label of the matching buoy.
        buoy_label: String,
    },
}

/// Maximum targets in an `EmergencyCoherence` message (C12: bounded collections).
#[allow(dead_code)] // Used transitively in truncate_fields (pub(crate), not yet wired to callers)
const EMERGENCY_TARGETS_MAX: usize = 50;

/// Maximum string field length for truncation.
#[allow(dead_code)] // Used transitively in truncate_fields (pub(crate), not yet wired to callers)
const STRING_FIELD_MAX: usize = 256;

impl PhaseMessage {
    /// Whether this message has a phase effect when applied.
    #[must_use]
    #[allow(dead_code)] // Designed API; callers will be added in L7 when field messaging is wired
    pub(crate) const fn has_phase_effect(&self) -> bool {
        matches!(
            self,
            Self::AttentionAlignment { .. }
                | Self::EmergencyCoherence { .. }
                | Self::ResonanceMatch { .. }
        )
    }

    /// Truncate all string fields to prevent oversized messages.
    #[allow(dead_code)] // Input sanitization API; wired to message ingestion in L7
    pub(crate) fn truncate_fields(&mut self) {
        match self {
            Self::AttentionAlignment { context, .. } => {
                *context = truncate_string(context, STRING_FIELD_MAX);
            }
            Self::ChimeraRequest { reason, .. } => {
                *reason = truncate_string(reason, STRING_FIELD_MAX);
            }
            Self::ConsensusWrite { payload, .. } => {
                *payload = truncate_string(payload, STRING_FIELD_MAX);
            }
            Self::EmergencyCoherence {
                targets, reason, ..
            } => {
                *reason = truncate_string(reason, STRING_FIELD_MAX);
                targets.truncate(EMERGENCY_TARGETS_MAX);
            }
            Self::ResonanceMatch { buoy_label, .. } => {
                *buoy_label = truncate_string(buoy_label, STRING_FIELD_MAX);
            }
        }
    }

    /// The sender sphere ID.
    #[must_use]
    #[allow(dead_code)] // Used in message routing (L7 m34_suggestions wires this in a future pass)
    pub(crate) const fn sender_id(&self) -> &PaneId {
        match self {
            Self::AttentionAlignment { from, .. }
            | Self::ChimeraRequest { from, .. }
            | Self::ConsensusWrite { from, .. }
            | Self::EmergencyCoherence { from, .. }
            | Self::ResonanceMatch { from, .. } => from,
        }
    }

    /// The primary target sphere ID (if applicable).
    ///
    /// Returns `None` for `EmergencyCoherence` (which has multiple targets).
    #[must_use]
    #[allow(dead_code)] // Part of message routing API; callers added in future L7 pass
    pub(crate) const fn target_id(&self) -> Option<&PaneId> {
        match self {
            Self::AttentionAlignment { to, .. }
            | Self::ChimeraRequest { to, .. }
            | Self::ConsensusWrite { to, .. }
            | Self::ResonanceMatch { to, .. } => Some(to),
            Self::EmergencyCoherence { .. } => None,
        }
    }

    /// Compute the phase adjustment this message would apply to a target sphere.
    ///
    /// Returns `(target_id, phase_delta)` pairs. `phase_delta` is in radians,
    /// already modulated by message-specific strength.
    #[must_use]
    #[allow(dead_code)] // Phase computation API for future L4 coupling integration
    pub(crate) fn phase_adjustments(
        &self,
        sender_phase: f64,
        target_phases: &std::collections::HashMap<PaneId, f64>,
    ) -> Vec<(PaneId, f64)> {
        match self {
            Self::AttentionAlignment { to, .. } => {
                if let Some(&target_phase) = target_phases.get(to) {
                    let delta = phase_diff(sender_phase, target_phase);
                    // Gentle steering: 5% of the phase difference
                    vec![(to.clone(), delta * 0.05)]
                } else {
                    Vec::new()
                }
            }
            Self::EmergencyCoherence { targets, .. } => targets
                .iter()
                .filter_map(|t| {
                    target_phases.get(t).map(|&target_phase| {
                        let delta = phase_diff(sender_phase, target_phase);
                        // Stronger pull: 15% of the phase difference
                        (t.clone(), delta * 0.15)
                    })
                })
                .collect(),
            Self::ResonanceMatch { to, .. } => {
                if let Some(&target_phase) = target_phases.get(to) {
                    let delta = phase_diff(sender_phase, target_phase);
                    // Moderate alignment: 10% of the phase difference
                    vec![(to.clone(), delta * 0.10)]
                } else {
                    Vec::new()
                }
            }
            // No phase effect
            Self::ChimeraRequest { .. } | Self::ConsensusWrite { .. } => Vec::new(),
        }
    }
}

// ──────────────────────────────────────────────────────────────
// Tests
// ──────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use approx::assert_relative_eq;
    use std::collections::HashMap;
    use std::f64::consts::PI;

    fn pid(s: &str) -> PaneId {
        PaneId::new(s)
    }

    // ── has_phase_effect ──

    #[test]
    fn attention_alignment_has_phase_effect() {
        let msg = PhaseMessage::AttentionAlignment {
            from: pid("a"),
            to: pid("b"),
            context: "test".into(),
        };
        assert!(msg.has_phase_effect());
    }

    #[test]
    fn chimera_request_no_phase_effect() {
        let msg = PhaseMessage::ChimeraRequest {
            from: pid("a"),
            to: pid("b"),
            reason: "test".into(),
        };
        assert!(!msg.has_phase_effect());
    }

    #[test]
    fn consensus_write_no_phase_effect() {
        let msg = PhaseMessage::ConsensusWrite {
            from: pid("a"),
            to: pid("b"),
            payload: "test".into(),
        };
        assert!(!msg.has_phase_effect());
    }

    #[test]
    fn emergency_coherence_has_phase_effect() {
        let msg = PhaseMessage::EmergencyCoherence {
            from: pid("a"),
            targets: vec![pid("b")],
            reason: "test".into(),
        };
        assert!(msg.has_phase_effect());
    }

    #[test]
    fn resonance_match_has_phase_effect() {
        let msg = PhaseMessage::ResonanceMatch {
            from: pid("a"),
            to: pid("b"),
            buoy_label: "primary".into(),
        };
        assert!(msg.has_phase_effect());
    }

    // ── sender_id ──

    #[test]
    fn sender_id_attention_alignment() {
        let msg = PhaseMessage::AttentionAlignment {
            from: pid("sender"),
            to: pid("target"),
            context: "x".into(),
        };
        assert_eq!(msg.sender_id().as_str(), "sender");
    }

    #[test]
    fn sender_id_chimera_request() {
        let msg = PhaseMessage::ChimeraRequest {
            from: pid("s"),
            to: pid("t"),
            reason: "x".into(),
        };
        assert_eq!(msg.sender_id().as_str(), "s");
    }

    #[test]
    fn sender_id_consensus_write() {
        let msg = PhaseMessage::ConsensusWrite {
            from: pid("w"),
            to: pid("r"),
            payload: "x".into(),
        };
        assert_eq!(msg.sender_id().as_str(), "w");
    }

    #[test]
    fn sender_id_emergency_coherence() {
        let msg = PhaseMessage::EmergencyCoherence {
            from: pid("e"),
            targets: vec![],
            reason: "x".into(),
        };
        assert_eq!(msg.sender_id().as_str(), "e");
    }

    #[test]
    fn sender_id_resonance_match() {
        let msg = PhaseMessage::ResonanceMatch {
            from: pid("r"),
            to: pid("t"),
            buoy_label: "x".into(),
        };
        assert_eq!(msg.sender_id().as_str(), "r");
    }

    // ── target_id ──

    #[test]
    fn target_id_attention_alignment() {
        let msg = PhaseMessage::AttentionAlignment {
            from: pid("a"),
            to: pid("target"),
            context: "x".into(),
        };
        assert_eq!(msg.target_id().map(PaneId::as_str), Some("target"));
    }

    #[test]
    fn target_id_emergency_coherence_is_none() {
        let msg = PhaseMessage::EmergencyCoherence {
            from: pid("a"),
            targets: vec![pid("b")],
            reason: "x".into(),
        };
        assert!(msg.target_id().is_none());
    }

    // ── truncate_fields ──

    #[test]
    fn truncate_attention_alignment_context() {
        let mut msg = PhaseMessage::AttentionAlignment {
            from: pid("a"),
            to: pid("b"),
            context: "x".repeat(500),
        };
        msg.truncate_fields();
        if let PhaseMessage::AttentionAlignment { context, .. } = &msg {
            assert!(context.len() <= STRING_FIELD_MAX);
        }
    }

    #[test]
    fn truncate_emergency_targets() {
        let targets: Vec<PaneId> = (0..100).map(|i| pid(&format!("t{i}"))).collect();
        let mut msg = PhaseMessage::EmergencyCoherence {
            from: pid("a"),
            targets,
            reason: "emergency".into(),
        };
        msg.truncate_fields();
        if let PhaseMessage::EmergencyCoherence { targets, .. } = &msg {
            assert!(targets.len() <= EMERGENCY_TARGETS_MAX);
        }
    }

    #[test]
    fn truncate_chimera_reason() {
        let mut msg = PhaseMessage::ChimeraRequest {
            from: pid("a"),
            to: pid("b"),
            reason: "x".repeat(500),
        };
        msg.truncate_fields();
        if let PhaseMessage::ChimeraRequest { reason, .. } = &msg {
            assert!(reason.len() <= STRING_FIELD_MAX);
        }
    }

    #[test]
    fn truncate_consensus_payload() {
        let mut msg = PhaseMessage::ConsensusWrite {
            from: pid("a"),
            to: pid("b"),
            payload: "x".repeat(500),
        };
        msg.truncate_fields();
        if let PhaseMessage::ConsensusWrite { payload, .. } = &msg {
            assert!(payload.len() <= STRING_FIELD_MAX);
        }
    }

    #[test]
    fn truncate_resonance_label() {
        let mut msg = PhaseMessage::ResonanceMatch {
            from: pid("a"),
            to: pid("b"),
            buoy_label: "x".repeat(500),
        };
        msg.truncate_fields();
        if let PhaseMessage::ResonanceMatch { buoy_label, .. } = &msg {
            assert!(buoy_label.len() <= STRING_FIELD_MAX);
        }
    }

    #[test]
    fn truncate_short_fields_unchanged() {
        let mut msg = PhaseMessage::AttentionAlignment {
            from: pid("a"),
            to: pid("b"),
            context: "short".into(),
        };
        msg.truncate_fields();
        if let PhaseMessage::AttentionAlignment { context, .. } = &msg {
            assert_eq!(context, "short");
        }
    }

    // ── phase_adjustments ──

    #[test]
    fn phase_adjustment_attention_alignment() {
        let msg = PhaseMessage::AttentionAlignment {
            from: pid("a"),
            to: pid("b"),
            context: "test".into(),
        };
        let mut target_phases = HashMap::new();
        target_phases.insert(pid("b"), 1.0);

        let adjustments = msg.phase_adjustments(0.0, &target_phases);
        assert_eq!(adjustments.len(), 1);
        assert_eq!(adjustments[0].0.as_str(), "b");
        // Sender at 0.0, target at 1.0 → delta = -1.0 → adjustment = -0.05
        assert_relative_eq!(adjustments[0].1, -0.05, epsilon = 1e-10);
    }

    #[test]
    fn phase_adjustment_emergency_coherence() {
        let msg = PhaseMessage::EmergencyCoherence {
            from: pid("a"),
            targets: vec![pid("b"), pid("c")],
            reason: "emergency".into(),
        };
        let mut target_phases = HashMap::new();
        target_phases.insert(pid("b"), 1.0);
        target_phases.insert(pid("c"), 2.0);

        let adjustments = msg.phase_adjustments(0.0, &target_phases);
        assert_eq!(adjustments.len(), 2);
    }

    #[test]
    fn phase_adjustment_emergency_missing_target() {
        let msg = PhaseMessage::EmergencyCoherence {
            from: pid("a"),
            targets: vec![pid("missing")],
            reason: "emergency".into(),
        };
        let target_phases = HashMap::new();
        let adjustments = msg.phase_adjustments(0.0, &target_phases);
        assert!(adjustments.is_empty());
    }

    #[test]
    fn phase_adjustment_resonance_match() {
        let msg = PhaseMessage::ResonanceMatch {
            from: pid("a"),
            to: pid("b"),
            buoy_label: "primary".into(),
        };
        let mut target_phases = HashMap::new();
        target_phases.insert(pid("b"), PI);

        let adjustments = msg.phase_adjustments(0.0, &target_phases);
        assert_eq!(adjustments.len(), 1);
    }

    #[test]
    fn phase_adjustment_chimera_no_effect() {
        let msg = PhaseMessage::ChimeraRequest {
            from: pid("a"),
            to: pid("b"),
            reason: "test".into(),
        };
        let mut target_phases = HashMap::new();
        target_phases.insert(pid("b"), 1.0);
        let adjustments = msg.phase_adjustments(0.0, &target_phases);
        assert!(adjustments.is_empty());
    }

    #[test]
    fn phase_adjustment_consensus_no_effect() {
        let msg = PhaseMessage::ConsensusWrite {
            from: pid("a"),
            to: pid("b"),
            payload: "data".into(),
        };
        let mut target_phases = HashMap::new();
        target_phases.insert(pid("b"), 1.0);
        let adjustments = msg.phase_adjustments(0.0, &target_phases);
        assert!(adjustments.is_empty());
    }

    #[test]
    fn phase_adjustment_same_phase_zero_delta() {
        let msg = PhaseMessage::AttentionAlignment {
            from: pid("a"),
            to: pid("b"),
            context: "test".into(),
        };
        let mut target_phases = HashMap::new();
        target_phases.insert(pid("b"), 0.0);
        let adjustments = msg.phase_adjustments(0.0, &target_phases);
        assert_eq!(adjustments.len(), 1);
        assert_relative_eq!(adjustments[0].1, 0.0, epsilon = 1e-10);
    }

    // ── Serde roundtrip ──

    #[test]
    fn attention_alignment_serde_roundtrip() {
        let msg = PhaseMessage::AttentionAlignment {
            from: pid("a"),
            to: pid("b"),
            context: "test".into(),
        };
        let json = serde_json::to_string(&msg).unwrap();
        let back: PhaseMessage = serde_json::from_str(&json).unwrap();
        assert_eq!(back.sender_id().as_str(), "a");
    }

    #[test]
    fn chimera_request_serde_roundtrip() {
        let msg = PhaseMessage::ChimeraRequest {
            from: pid("a"),
            to: pid("b"),
            reason: "diverge".into(),
        };
        let json = serde_json::to_string(&msg).unwrap();
        let back: PhaseMessage = serde_json::from_str(&json).unwrap();
        assert!(!back.has_phase_effect());
    }

    #[test]
    fn emergency_coherence_serde_roundtrip() {
        let msg = PhaseMessage::EmergencyCoherence {
            from: pid("a"),
            targets: vec![pid("b"), pid("c"), pid("d")],
            reason: "crisis".into(),
        };
        let json = serde_json::to_string(&msg).unwrap();
        let back: PhaseMessage = serde_json::from_str(&json).unwrap();
        if let PhaseMessage::EmergencyCoherence { targets, .. } = back {
            assert_eq!(targets.len(), 3);
        } else {
            panic!("wrong variant");
        }
    }

    #[test]
    fn resonance_match_serde_roundtrip() {
        let msg = PhaseMessage::ResonanceMatch {
            from: pid("a"),
            to: pid("b"),
            buoy_label: "primary".into(),
        };
        let json = serde_json::to_string(&msg).unwrap();
        let back: PhaseMessage = serde_json::from_str(&json).unwrap();
        assert!(back.has_phase_effect());
    }

    #[test]
    fn consensus_write_serde_roundtrip() {
        let msg = PhaseMessage::ConsensusWrite {
            from: pid("a"),
            to: pid("b"),
            payload: "data".into(),
        };
        let json = serde_json::to_string(&msg).unwrap();
        let back: PhaseMessage = serde_json::from_str(&json).unwrap();
        assert!(!back.has_phase_effect());
    }

    // ── Edge cases ──

    #[test]
    fn empty_string_fields_ok() {
        let msg = PhaseMessage::AttentionAlignment {
            from: pid("a"),
            to: pid("b"),
            context: String::new(),
        };
        assert!(msg.has_phase_effect());
        assert_eq!(msg.sender_id().as_str(), "a");
    }

    #[test]
    fn empty_targets_emergency() {
        let msg = PhaseMessage::EmergencyCoherence {
            from: pid("a"),
            targets: Vec::new(),
            reason: "none".into(),
        };
        assert!(msg.has_phase_effect());
        let adjustments = msg.phase_adjustments(0.0, &HashMap::new());
        assert!(adjustments.is_empty());
    }
}
