//! # M34: Field Suggestions
//!
//! Field-driven suggestions generated by the conductor: exploratory, engagement,
//! collaboration. Sphere autonomy filtering: receptivity gate 0.3, `opt_out_cross_activation` check.
//!
//! ## Layer: L7 | Module: M34 | Dependencies: L1, L3 (M11, M12)
//! ## NA: NA-P-16 (sphere-invokable, not auto-invoked)

use std::collections::{HashMap, VecDeque};
use std::fmt;

use crate::m1_foundation::m01_core_types::{FieldAction, PaneId};
use crate::m3_field::{
    m11_sphere::PaneSphere,
    m12_field_state::FieldDecision,
};

// ──────────────────────────────────────────────────────────────
// Constants
// ──────────────────────────────────────────────────────────────

/// Minimum receptivity for a sphere to receive suggestions.
const RECEPTIVITY_GATE: f64 = 0.3;

/// Maximum suggestions per tick.
const MAX_SUGGESTIONS_PER_TICK: usize = 20;

/// Minimum confidence for a suggestion to be emitted.
const MIN_CONFIDENCE: f64 = 0.1;

// ──────────────────────────────────────────────────────────────
// SuggestionType
// ──────────────────────────────────────────────────────────────

/// Type of field-driven suggestion.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum SuggestionType {
    /// Suggest increasing coherence (phase alignment) for a sphere.
    SuggestCoherence,
    /// Suggest increasing divergence (phase exploration) for a sphere.
    SuggestDivergence,
    /// Suggest a cascade handoff to transfer work.
    SuggestCascade,
    /// Suggest reseeding (frequency reset) for a stale sphere.
    SuggestReseed,
}

impl fmt::Display for SuggestionType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::SuggestCoherence => write!(f, "SuggestCoherence"),
            Self::SuggestDivergence => write!(f, "SuggestDivergence"),
            Self::SuggestCascade => write!(f, "SuggestCascade"),
            Self::SuggestReseed => write!(f, "SuggestReseed"),
        }
    }
}

// ──────────────────────────────────────────────────────────────
// FieldSuggestion
// ──────────────────────────────────────────────────────────────

/// A field-driven suggestion for a specific sphere.
///
/// Suggestions are generated by the `SuggestionEngine` and filtered by
/// sphere autonomy (receptivity gate, opt-out checks).
#[derive(Debug, Clone)]
pub struct FieldSuggestion {
    /// Type of suggestion.
    pub suggestion_type: SuggestionType,
    /// Target sphere for this suggestion.
    pub target_sphere: PaneId,
    /// Human-readable reason for the suggestion.
    pub reason: String,
    /// Confidence level (0.0–1.0).
    pub confidence: f64,
    /// Tick at which the suggestion was generated.
    pub tick: u64,
}

impl FieldSuggestion {
    /// Create a new field suggestion.
    #[must_use]
    pub fn new(
        suggestion_type: SuggestionType,
        target_sphere: PaneId,
        reason: String,
        confidence: f64,
        tick: u64,
    ) -> Self {
        Self {
            suggestion_type,
            target_sphere,
            reason,
            confidence: confidence.clamp(0.0, 1.0),
            tick,
        }
    }

    /// Whether this suggestion passes the minimum confidence threshold.
    #[must_use]
    pub fn is_above_threshold(&self) -> bool {
        self.confidence >= MIN_CONFIDENCE
    }
}

impl fmt::Display for FieldSuggestion {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "[{}] {} -> {} (conf={:.2})",
            self.tick, self.suggestion_type, self.target_sphere, self.confidence
        )
    }
}

// ──────────────────────────────────────────────────────────────
// SuggestionEngine
// ──────────────────────────────────────────────────────────────

/// Engine that generates field-driven suggestions from the current field decision.
///
/// Suggestions are *never* auto-invoked (NA-P-16). They are published as events
/// on the bus for spheres to optionally act upon.
#[derive(Debug)]
pub struct SuggestionEngine {
    /// Recent suggestions (bounded ring buffer — O(1) push and eviction via `VecDeque`).
    recent: VecDeque<FieldSuggestion>,
    /// Maximum recent suggestions to retain.
    max_recent: usize,
}

impl SuggestionEngine {
    /// Create a new suggestion engine.
    #[must_use]
    pub const fn new() -> Self {
        Self {
            recent: VecDeque::new(),
            max_recent: 200,
        }
    }

    /// Generate suggestions from the current field decision.
    ///
    /// Filters by sphere autonomy (receptivity + opt-out checks).
    #[allow(clippy::implicit_hasher)]
    pub fn generate(
        &mut self,
        decision: &FieldDecision,
        spheres: &HashMap<PaneId, PaneSphere>,
    ) -> Vec<FieldSuggestion> {
        let mut suggestions = Vec::new();

        match decision.action {
            FieldAction::NeedsCoherence => {
                self.suggest_coherence(decision, spheres, &mut suggestions);
            }
            FieldAction::NeedsDivergence | FieldAction::OverSynchronized => {
                self.suggest_divergence(decision, spheres, &mut suggestions);
            }
            FieldAction::IdleFleet => {
                self.suggest_cascade_for_idle(decision, spheres, &mut suggestions);
            }
            FieldAction::HasBlockedAgents => {
                self.suggest_reseed_for_blocked(decision, spheres, &mut suggestions);
            }
            FieldAction::Stable | FieldAction::FreshFleet | FieldAction::Recovering => {
                // No suggestions for stable/fresh/recovering states
            }
        }

        // Filter by autonomy
        let filtered: Vec<FieldSuggestion> = suggestions
            .into_iter()
            .filter(|s| passes_autonomy_filter(s, spheres))
            .filter(FieldSuggestion::is_above_threshold)
            .take(MAX_SUGGESTIONS_PER_TICK)
            .collect();

        // Store in recent buffer — push_back + pop_front is O(1) on VecDeque
        for s in &filtered {
            if self.recent.len() >= self.max_recent {
                self.recent.pop_front();
            }
            self.recent.push_back(s.clone());
        }

        filtered
    }

    /// Get recent suggestions.
    #[must_use]
    pub fn recent_suggestions(&self, n: usize) -> Vec<&FieldSuggestion> {
        self.recent.iter().rev().take(n).collect()
    }

    /// Total suggestions generated (in the recent buffer).
    #[must_use]
    pub fn total_generated(&self) -> usize {
        self.recent.len()
    }

    /// Clear the recent buffer.
    pub fn clear(&mut self) {
        self.recent.clear();
    }

    // ── Suggestion generators ──

    /// Suggest coherence for idle spheres when the field needs coherence.
    #[allow(clippy::unused_self)]
    fn suggest_coherence(
        &self,
        decision: &FieldDecision,
        spheres: &HashMap<PaneId, PaneSphere>,
        out: &mut Vec<FieldSuggestion>,
    ) {
        for id in &decision.idle_spheres {
            if let Some(sphere) = spheres.get(id) {
                let confidence = decision.coherence_pressure.min(1.0)
                    * sphere.receptivity;
                out.push(FieldSuggestion::new(
                    SuggestionType::SuggestCoherence,
                    id.clone(),
                    format!(
                        "field r={:.2} trending down, sphere {} is idle",
                        decision.r,
                        sphere.persona
                    ),
                    confidence,
                    decision.tick,
                ));
            }
        }
    }

    /// Suggest divergence for working spheres when the field is over-synchronized.
    #[allow(clippy::unused_self)]
    fn suggest_divergence(
        &self,
        decision: &FieldDecision,
        spheres: &HashMap<PaneId, PaneSphere>,
        out: &mut Vec<FieldSuggestion>,
    ) {
        for id in &decision.working_spheres {
            if let Some(sphere) = spheres.get(id) {
                let confidence = decision.divergence_pressure.min(1.0)
                    * (1.0 - sphere.work_signature.focus).max(0.1);
                out.push(FieldSuggestion::new(
                    SuggestionType::SuggestDivergence,
                    id.clone(),
                    format!(
                        "field r={:.2} too high, sphere {} could explore",
                        decision.r,
                        sphere.persona
                    ),
                    confidence,
                    decision.tick,
                ));
            }
        }
    }

    /// Suggest cascade for idle spheres when the fleet is mostly idle.
    #[allow(clippy::unused_self)]
    fn suggest_cascade_for_idle(
        &self,
        decision: &FieldDecision,
        spheres: &HashMap<PaneId, PaneSphere>,
        out: &mut Vec<FieldSuggestion>,
    ) {
        // Only suggest cascades if there are working spheres that could hand off
        if decision.working_spheres.is_empty() {
            return;
        }

        for id in &decision.idle_spheres {
            if let Some(sphere) = spheres.get(id) {
                let confidence = 0.5 * sphere.receptivity;
                out.push(FieldSuggestion::new(
                    SuggestionType::SuggestCascade,
                    id.clone(),
                    format!(
                        "idle fleet detected, {} could receive cascade",
                        sphere.persona
                    ),
                    confidence,
                    decision.tick,
                ));
            }
        }
    }

    /// Suggest reseed for blocked spheres.
    #[allow(clippy::unused_self)]
    fn suggest_reseed_for_blocked(
        &self,
        decision: &FieldDecision,
        spheres: &HashMap<PaneId, PaneSphere>,
        out: &mut Vec<FieldSuggestion>,
    ) {
        for id in &decision.blocked_spheres {
            if let Some(sphere) = spheres.get(id) {
                out.push(FieldSuggestion::new(
                    SuggestionType::SuggestReseed,
                    id.clone(),
                    format!("sphere {} is blocked, reseed may help", sphere.persona),
                    0.7,
                    decision.tick,
                ));
            }
        }
    }
}

impl Default for SuggestionEngine {
    fn default() -> Self {
        Self::new()
    }
}

// ──────────────────────────────────────────────────────────────
// Autonomy filter
// ──────────────────────────────────────────────────────────────

/// Check whether a suggestion passes the sphere's autonomy filter.
///
/// A suggestion is filtered out if:
/// - The target sphere is not found.
/// - The target sphere has `opt_out_cross_activation`.
/// - The target sphere's receptivity is below the gate.
#[allow(clippy::implicit_hasher)]
fn passes_autonomy_filter(
    suggestion: &FieldSuggestion,
    spheres: &HashMap<PaneId, PaneSphere>,
) -> bool {
    let Some(sphere) = spheres.get(&suggestion.target_sphere) else {
        return false;
    };
    if sphere.opt_out_cross_activation {
        return false;
    }
    sphere.receptivity >= RECEPTIVITY_GATE
}

// ──────────────────────────────────────────────────────────────
// Tests
// ──────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::m1_foundation::m01_core_types::{FleetMode, PaneStatus, RTrend};
    use crate::m3_field::m13_chimera::ChimeraRouting;
    use approx::assert_relative_eq;

    fn pid(s: &str) -> PaneId {
        PaneId::new(s)
    }

    fn make_sphere(id: &str, status: PaneStatus) -> PaneSphere {
        let mut s = PaneSphere::new(pid(id), id.into(), 0.1).unwrap();
        s.status = status;
        s
    }

    fn make_spheres(entries: &[(&str, PaneStatus)]) -> HashMap<PaneId, PaneSphere> {
        entries
            .iter()
            .map(|(id, status)| (pid(id), make_sphere(id, *status)))
            .collect()
    }

    fn make_decision(action: FieldAction) -> FieldDecision {
        FieldDecision {
            action,
            r: 0.5,
            r_trend: RTrend::Stable,
            idle_spheres: Vec::new(),
            blocked_spheres: Vec::new(),
            working_spheres: Vec::new(),
            routing: ChimeraRouting::default(),
            tunnel_count: 0,
            strongest_tunnel: None,
            tick: 10,
            coherence_pressure: 0.0,
            divergence_pressure: 0.0,
            fleet_mode: FleetMode::Full,
        }
    }

    // ── SuggestionType ──

    #[test]
    fn suggestion_type_display() {
        assert_eq!(
            format!("{}", SuggestionType::SuggestCoherence),
            "SuggestCoherence"
        );
        assert_eq!(
            format!("{}", SuggestionType::SuggestDivergence),
            "SuggestDivergence"
        );
        assert_eq!(
            format!("{}", SuggestionType::SuggestCascade),
            "SuggestCascade"
        );
        assert_eq!(
            format!("{}", SuggestionType::SuggestReseed),
            "SuggestReseed"
        );
    }

    #[test]
    fn suggestion_type_equality() {
        assert_eq!(SuggestionType::SuggestCoherence, SuggestionType::SuggestCoherence);
        assert_ne!(SuggestionType::SuggestCoherence, SuggestionType::SuggestDivergence);
    }

    // ── FieldSuggestion ──

    #[test]
    fn suggestion_creation() {
        let s = FieldSuggestion::new(
            SuggestionType::SuggestCoherence,
            pid("alpha"),
            "test reason".into(),
            0.8,
            42,
        );
        assert_eq!(s.suggestion_type, SuggestionType::SuggestCoherence);
        assert_eq!(s.target_sphere.as_str(), "alpha");
        assert_relative_eq!(s.confidence, 0.8);
        assert_eq!(s.tick, 42);
    }

    #[test]
    fn suggestion_confidence_clamped() {
        let s = FieldSuggestion::new(
            SuggestionType::SuggestCoherence,
            pid("a"),
            "reason".into(),
            1.5,
            0,
        );
        assert_relative_eq!(s.confidence, 1.0);

        let s2 = FieldSuggestion::new(
            SuggestionType::SuggestCoherence,
            pid("a"),
            "reason".into(),
            -0.5,
            0,
        );
        assert_relative_eq!(s2.confidence, 0.0);
    }

    #[test]
    fn suggestion_above_threshold() {
        let s = FieldSuggestion::new(
            SuggestionType::SuggestCoherence,
            pid("a"),
            "reason".into(),
            0.5,
            0,
        );
        assert!(s.is_above_threshold());
    }

    #[test]
    fn suggestion_below_threshold() {
        let s = FieldSuggestion::new(
            SuggestionType::SuggestCoherence,
            pid("a"),
            "reason".into(),
            0.05,
            0,
        );
        assert!(!s.is_above_threshold());
    }

    #[test]
    fn suggestion_display() {
        let s = FieldSuggestion::new(
            SuggestionType::SuggestDivergence,
            pid("beta"),
            "reason".into(),
            0.75,
            100,
        );
        let display = format!("{s}");
        assert!(display.contains("100"));
        assert!(display.contains("SuggestDivergence"));
        assert!(display.contains("beta"));
    }

    // ── SuggestionEngine ──

    #[test]
    fn engine_new_empty() {
        let engine = SuggestionEngine::new();
        assert_eq!(engine.total_generated(), 0);
    }

    #[test]
    fn engine_default_empty() {
        let engine = SuggestionEngine::default();
        assert_eq!(engine.total_generated(), 0);
    }

    #[test]
    fn engine_generate_stable_no_suggestions() {
        let mut engine = SuggestionEngine::new();
        let decision = make_decision(FieldAction::Stable);
        let spheres = make_spheres(&[("a", PaneStatus::Idle)]);
        let suggestions = engine.generate(&decision, &spheres);
        assert!(suggestions.is_empty());
    }

    #[test]
    fn engine_generate_fresh_fleet_no_suggestions() {
        let mut engine = SuggestionEngine::new();
        let decision = make_decision(FieldAction::FreshFleet);
        let spheres = make_spheres(&[("a", PaneStatus::Idle)]);
        let suggestions = engine.generate(&decision, &spheres);
        assert!(suggestions.is_empty());
    }

    #[test]
    fn engine_generate_recovering_no_suggestions() {
        let mut engine = SuggestionEngine::new();
        let decision = make_decision(FieldAction::Recovering);
        let spheres = make_spheres(&[("a", PaneStatus::Idle)]);
        let suggestions = engine.generate(&decision, &spheres);
        assert!(suggestions.is_empty());
    }

    #[test]
    fn engine_generate_needs_coherence() {
        let mut engine = SuggestionEngine::new();
        let mut decision = make_decision(FieldAction::NeedsCoherence);
        decision.idle_spheres = vec![pid("idle-1")];
        decision.coherence_pressure = 0.8;
        decision.r = 0.3;
        let spheres = make_spheres(&[("idle-1", PaneStatus::Idle)]);
        let suggestions = engine.generate(&decision, &spheres);
        assert!(!suggestions.is_empty());
        assert_eq!(suggestions[0].suggestion_type, SuggestionType::SuggestCoherence);
    }

    #[test]
    fn engine_generate_needs_divergence() {
        let mut engine = SuggestionEngine::new();
        let mut decision = make_decision(FieldAction::NeedsDivergence);
        decision.working_spheres = vec![pid("worker")];
        decision.divergence_pressure = 0.5;
        let spheres = make_spheres(&[("worker", PaneStatus::Working)]);
        let suggestions = engine.generate(&decision, &spheres);
        assert!(!suggestions.is_empty());
        assert_eq!(suggestions[0].suggestion_type, SuggestionType::SuggestDivergence);
    }

    #[test]
    fn engine_generate_over_synchronized() {
        let mut engine = SuggestionEngine::new();
        let mut decision = make_decision(FieldAction::OverSynchronized);
        decision.working_spheres = vec![pid("worker")];
        decision.divergence_pressure = 0.7;
        let spheres = make_spheres(&[("worker", PaneStatus::Working)]);
        let suggestions = engine.generate(&decision, &spheres);
        assert!(!suggestions.is_empty());
        assert_eq!(suggestions[0].suggestion_type, SuggestionType::SuggestDivergence);
    }

    #[test]
    fn engine_generate_idle_fleet_cascade() {
        let mut engine = SuggestionEngine::new();
        let mut decision = make_decision(FieldAction::IdleFleet);
        decision.idle_spheres = vec![pid("idle-1")];
        decision.working_spheres = vec![pid("worker")];
        let spheres = make_spheres(&[
            ("idle-1", PaneStatus::Idle),
            ("worker", PaneStatus::Working),
        ]);
        let suggestions = engine.generate(&decision, &spheres);
        assert!(!suggestions.is_empty());
        assert_eq!(suggestions[0].suggestion_type, SuggestionType::SuggestCascade);
    }

    #[test]
    fn engine_generate_idle_fleet_no_workers_no_cascade() {
        let mut engine = SuggestionEngine::new();
        let mut decision = make_decision(FieldAction::IdleFleet);
        decision.idle_spheres = vec![pid("idle-1")];
        decision.working_spheres = Vec::new();
        let spheres = make_spheres(&[("idle-1", PaneStatus::Idle)]);
        let suggestions = engine.generate(&decision, &spheres);
        assert!(suggestions.is_empty());
    }

    #[test]
    fn engine_generate_blocked_reseed() {
        let mut engine = SuggestionEngine::new();
        let mut decision = make_decision(FieldAction::HasBlockedAgents);
        decision.blocked_spheres = vec![pid("blocked")];
        let spheres = make_spheres(&[("blocked", PaneStatus::Blocked)]);
        let suggestions = engine.generate(&decision, &spheres);
        assert!(!suggestions.is_empty());
        assert_eq!(suggestions[0].suggestion_type, SuggestionType::SuggestReseed);
    }

    // ── Autonomy filtering ──

    #[test]
    fn autonomy_filter_passes_receptive() {
        let spheres = make_spheres(&[("a", PaneStatus::Idle)]);
        let s = FieldSuggestion::new(
            SuggestionType::SuggestCoherence,
            pid("a"),
            "reason".into(),
            0.5,
            0,
        );
        assert!(passes_autonomy_filter(&s, &spheres));
    }

    #[test]
    fn autonomy_filter_rejects_low_receptivity() {
        let mut spheres = make_spheres(&[("a", PaneStatus::Idle)]);
        spheres.get_mut(&pid("a")).unwrap().receptivity = 0.1;
        let s = FieldSuggestion::new(
            SuggestionType::SuggestCoherence,
            pid("a"),
            "reason".into(),
            0.5,
            0,
        );
        assert!(!passes_autonomy_filter(&s, &spheres));
    }

    #[test]
    fn autonomy_filter_rejects_opted_out() {
        let mut spheres = make_spheres(&[("a", PaneStatus::Idle)]);
        spheres.get_mut(&pid("a")).unwrap().opt_out_cross_activation = true;
        let s = FieldSuggestion::new(
            SuggestionType::SuggestCoherence,
            pid("a"),
            "reason".into(),
            0.5,
            0,
        );
        assert!(!passes_autonomy_filter(&s, &spheres));
    }

    #[test]
    fn autonomy_filter_rejects_missing_sphere() {
        let spheres = HashMap::new();
        let s = FieldSuggestion::new(
            SuggestionType::SuggestCoherence,
            pid("missing"),
            "reason".into(),
            0.5,
            0,
        );
        assert!(!passes_autonomy_filter(&s, &spheres));
    }

    // ── Engine buffer management ──

    #[test]
    fn engine_recent_suggestions() {
        let mut engine = SuggestionEngine::new();
        let mut decision = make_decision(FieldAction::NeedsCoherence);
        decision.idle_spheres = vec![pid("a"), pid("b")];
        decision.coherence_pressure = 0.8;
        let spheres = make_spheres(&[("a", PaneStatus::Idle), ("b", PaneStatus::Idle)]);
        engine.generate(&decision, &spheres);
        let recent = engine.recent_suggestions(10);
        assert!(!recent.is_empty());
    }

    #[test]
    fn engine_clear() {
        let mut engine = SuggestionEngine::new();
        let mut decision = make_decision(FieldAction::NeedsCoherence);
        decision.idle_spheres = vec![pid("a")];
        decision.coherence_pressure = 0.8;
        let spheres = make_spheres(&[("a", PaneStatus::Idle)]);
        engine.generate(&decision, &spheres);
        engine.clear();
        assert_eq!(engine.total_generated(), 0);
    }

    #[test]
    fn engine_caps_at_max() {
        let mut engine = SuggestionEngine::new();
        let mut decision = make_decision(FieldAction::NeedsCoherence);
        decision.coherence_pressure = 0.8;

        // Generate many suggestions across many ticks
        for tick in 0..300 {
            decision.tick = tick;
            let ids: Vec<PaneId> = (0..5).map(|i| pid(&format!("s{i}"))).collect();
            decision.idle_spheres = ids.clone();
            let spheres: HashMap<PaneId, PaneSphere> = ids
                .into_iter()
                .map(|id| {
                    let s = PaneSphere::new(id.clone(), "t".into(), 0.1).unwrap();
                    (id, s)
                })
                .collect();
            engine.generate(&decision, &spheres);
        }
        assert!(engine.total_generated() <= engine.max_recent);
    }

    // ── Edge cases ──

    #[test]
    fn generate_with_empty_spheres() {
        let mut engine = SuggestionEngine::new();
        let mut decision = make_decision(FieldAction::NeedsCoherence);
        decision.idle_spheres = vec![pid("nonexistent")];
        let spheres = HashMap::new();
        let suggestions = engine.generate(&decision, &spheres);
        assert!(suggestions.is_empty());
    }

    #[test]
    fn generate_with_all_opted_out() {
        let mut engine = SuggestionEngine::new();
        let mut decision = make_decision(FieldAction::NeedsCoherence);
        decision.idle_spheres = vec![pid("a")];
        decision.coherence_pressure = 0.8;
        let mut spheres = make_spheres(&[("a", PaneStatus::Idle)]);
        spheres.get_mut(&pid("a")).unwrap().opt_out_cross_activation = true;
        let suggestions = engine.generate(&decision, &spheres);
        assert!(suggestions.is_empty());
    }

    #[test]
    fn generate_divergence_with_high_focus() {
        let mut engine = SuggestionEngine::new();
        let mut decision = make_decision(FieldAction::NeedsDivergence);
        decision.working_spheres = vec![pid("focused")];
        decision.divergence_pressure = 0.5;
        let mut spheres = make_spheres(&[("focused", PaneStatus::Working)]);
        spheres.get_mut(&pid("focused")).unwrap().work_signature.focus = 0.9;
        let suggestions = engine.generate(&decision, &spheres);
        // Should still generate a suggestion, but with lower confidence
        if !suggestions.is_empty() {
            assert!(suggestions[0].confidence < 0.5);
        }
    }

    #[test]
    fn suggestion_at_receptivity_boundary() {
        let mut spheres = make_spheres(&[("edge", PaneStatus::Idle)]);
        spheres.get_mut(&pid("edge")).unwrap().receptivity = RECEPTIVITY_GATE;
        let s = FieldSuggestion::new(
            SuggestionType::SuggestCoherence,
            pid("edge"),
            "reason".into(),
            0.5,
            0,
        );
        assert!(passes_autonomy_filter(&s, &spheres));
    }

    #[test]
    fn suggestion_just_below_receptivity() {
        let mut spheres = make_spheres(&[("edge", PaneStatus::Idle)]);
        spheres.get_mut(&pid("edge")).unwrap().receptivity = RECEPTIVITY_GATE - 0.01;
        let s = FieldSuggestion::new(
            SuggestionType::SuggestCoherence,
            pid("edge"),
            "reason".into(),
            0.5,
            0,
        );
        assert!(!passes_autonomy_filter(&s, &spheres));
    }
}
