//! # M34: Field Suggestions
//! Field-driven suggestions generated by conductor: exploratory, engagement, collaboration.
//! Sphere autonomy filtering: receptivity gate 0.3, `opt_out_cross_activation` check.
//! ## Layer: L7 | Module: M34 | Dependencies: L1, L3 (M11, M12)
//! ## NA: NA-P-16 (sphere-invokable, not auto-invoked)
